var warriors = { players:
   [ { player_number: '21',
       name: 'Ian Clark',
       position: 'G',
       height: '6\' 3"',
       weight: '175',
       age: '25',
       experience: '3',
       birth_place: 'Memphis, Tennessee',
       college: 'Belmont' },
     { player_number: '30',
       name: 'Stephen Curry',
       position: 'G',
       height: '6\' 3"',
       weight: '190',
       age: '28',
       experience: '7',
       birth_place: 'Akron, Ohio',
       college: 'Davidson' },
     { player_number: '35',
       name: 'Kevin Durant',
       position: 'F',
       height: '6\' 9"',
       weight: '240',
       age: '28',
       experience: '9',
       birth_place: 'Washington, District of Columbia',
       college: 'Texas' },
     { player_number: '23',
       name: 'Draymond Green',
       position: 'F',
       height: '6\' 7"',
       weight: '230',
       age: '26',
       experience: '4',
       birth_place: 'Saginaw, Michigan',
       college: 'Michigan State' },
     { player_number: '9',
       name: 'Andre Iguodala',
       position: 'GF',
       height: '6\' 6"',
       weight: '207',
       age: '32',
       experience: '12',
       birth_place: 'Springfield, Illinois',
       college: 'Arizona' },
     { player_number: '39',
       name: 'Damian Jones',
       position: 'C',
       height: '7\' 0"',
       weight: '245',
       age: '21',
       experience: 'R',
       birth_place: 'Baton Rouge, Louisiana',
       college: 'Vanderbilt' },
     { player_number: '34',
       name: 'Shaun Livingston',
       position: 'G',
       height: '6\' 7"',
       weight: '182',
       age: '31',
       experience: '12',
       birth_place: 'Peoria, Illinois',
       college: 'None' },
     { player_number: '36',
       name: 'Kevon Looney',
       position: 'PF',
       height: '6\' 9"',
       weight: '220',
       age: '20',
       experience: '1',
       birth_place: 'Milwaukee, Wisconsin',
       college: 'UCLA' },
     { player_number: '20',
       name: 'James Michael McAdoo',
       position: 'PF',
       height: '6\' 9"',
       weight: '230',
       age: '23',
       experience: '2',
       birth_place: 'Norfolk, Virginia',
       college: 'North Carolina' },
     { player_number: '8',
       name: 'Patrick McCaw',
       position: 'SG',
       height: '6\' 7"',
       weight: '185',
       age: '21',
       experience: 'R',
       birth_place: 'St. Louis, Missouri',
       college: 'UNLV' },
     { player_number: '27',
       name: 'Zaza Pachulia',
       position: 'C',
       height: '6\' 11"',
       weight: '275',
       age: '32',
       experience: '13',
       birth_place: 'Tbilisi, USSR',
       college: 'None' },
     { player_number: '11',
       name: 'Klay Thompson',
       position: 'GF',
       height: '6\' 7"',
       weight: '215',
       age: '26',
       experience: '5',
       birth_place: 'Los Angeles, California',
       college: 'Washington State' },
     { player_number: '18',
       name: 'Anderson Varejao',
       position: 'FC',
       height: '6\' 11"',
       weight: '273',
       age: '34',
       experience: '12',
       birth_place: 'Santa Teresa, Brazil',
       college: 'None' },
     { player_number: '3',
       name: 'David West',
       position: 'PF',
       height: '6\' 9"',
       weight: '240',
       age: '36',
       experience: '13',
       birth_place: 'Teaneck, New Jersey',
       college: 'Xavier' } ],
  name: 'Golden State Warriors',
  acronym: 'gsw' }

  console.log(warriors.players.length);